name: Build and Publish LaTeX document

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: main.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: main-pdf
          path: ./artifact

      - name: Create index.html
        run: |
          echo '<!DOCTYPE html>' > ./artifact/index.html
          echo '<html>' >> ./artifact/index.html
          echo '<head>' >> ./artifact/index.html
          echo '  <meta http-equiv="refresh" content="0; url=main.pdf">' >> ./artifact/index.html
          echo '</head>' >> ./artifact/index.html
          echo '<body>' >> ./artifact/index.html
          echo '  <p>If you are not redirected, <a href="main.pdf">click here</a>.</p>' >> ./artifact/index.html
          echo '</body>' >> ./artifact/index.html
          echo '</html>' >> ./artifact/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./artifact
          publish_branch: gh-pages
